@startuml

title __SRC's Class Diagram__\n

  package  {
    class BuyGUI {
        ~ p : JPanel
        ~ p2 : JPanel
        ~ textArea : JTextArea
        ~ scrollPane : JScrollPane
        ~ itemString : String[]
        ~ itemList : JComboBox
        + BuyGUI()
        + actionPerformed()
    }
  }

  package  {
    class CheckoutGUI {
        - name : String
        - phoneNumber : String
        - address : String
        - towncity : String
        - postcode : String
        - country : String
        - cardNumber : String
        - expiryDate : String
        - cvv : String
        {static} ~ summary : String
        ~ nametxt : JTextField
        ~ addresstxt : JTextField
        + CheckoutGUI()
    }
  }

  package  {
    class CompareGUI {
        ~ p : JPanel
        ~ p2 : JPanel
        ~ textArea : JTextArea
        ~ textArea1 : JTextArea
        ~ scrollPane : JScrollPane
        ~ scrollPane1 : JScrollPane
        ~ itemString : String[]
        ~ itemList : JComboBox
        ~ itemList2 : JComboBox
        + CompareGUI()
        + actionPerformed()
    }
  }
  

  package  {
    class HomeGUI {
        + HomeGUI()
    }
  }

  package  {
    class LoginGUI {
        ~ usernameField : JTextField
        ~ passwordField : JPasswordField
        ~ LoginButton : JButton
        + LoginGUI()
        + actionPerformed()
    }
  }
  

  package  {
    class Phone {
    }
  }
  

  package  {
    class PhoneDriver {
        {static} + main()
    }
  }
  

  package  {
    class newPhone {
        - name : String
        - dimensions : String
        - weight : double
        - displayType : String
        - displaySize : double
        - Resolution : String
        - multitouch : String
        - os : String
        - cpu : String
        - fingerprint : String
        - cost : double
        {static} - allPhones : ArrayList<newPhone>
        + newPhone()
        + newPhone()
        + getName()
        + setName()
        + getDimensions()
        + setDimensions()
        + getWeight()
        + setWeight()
        + getDisplayType()
        + setDisplayType()
        + getDisplaySize()
        + setDisplaySize()
        + getResolution()
        + setResolution()
        + getMultitouch()
        + setMultitouch()
        + getOs()
        + setOs()
        + getCpu()
        + setCpu()
        + getFingerprint()
        + setFingerprint()
        + getCost()
        + setCost()
        + toString()
        {static} + createPhone()
        {static} + getAllPhones()
    }
  }
  

  package  {
    class oldPhone {
        - name : String
        - dimensions : String
        - weight : double
        - displayType : String
        - displaySize : double
        - Resolution : String
        - multitouch : String
        - os : String
        - cpu : String
        - fingerprint : String
        - cost : double
        - keyboardType : String
        - flip : String
        + getKeyboardType()
        + setKeyboardType()
        + getFlip()
        + setFlip()
        + getName()
        + setName()
        + getDimensions()
        + setDimensions()
        + getWeight()
        + setWeight()
        + getDisplayType()
        + setDisplayType()
        + getDisplaySize()
        + setDisplaySize()
        + getResolution()
        + setResolution()
        + getMultitouch()
        + setMultitouch()
        + getOs()
        + setOs()
        + getCpu()
        + setCpu()
        + getFingerprint()
        + setFingerprint()
        + getCost()
        + setCost()
        + oldPhone()
        + oldPhone()
        + toString()
    }
  }
right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
